apiVersion: v1
kind: Secret
metadata:
  name: capture-service-secrets
  namespace: treetracker-webapp-mvp
  labels:
    app: treetracker-capture-service
type: Opaque
stringData:
  FABRIC_ADMIN_USER: "admin"
  FABRIC_ADMIN_PASSWORD: "adminpw"
  DATABASE_URL: "postgresql://treetracker:password@postgres:5432/treetracker_captures"